global:
  scrape_interval: 15s

rule_files:
  - "alerts/*.yaml"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
      - targets: ['192.168.11.11:9100']
      - targets: ['192.168.11.12:9100']
      - targets: ['192.168.11.13:9100']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
      
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://localhost:8080
        - http://192.168.11.11:3000
        - http://192.168.11.12
        - http://192.168.11.13
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

