---
- hosts: apache2
  become: true
  tasks:
    - name: stop apache2
      service:
          name: apache2
          state: stopped
    - name: ensure apache2 is not installed
      apt: name=apache2 state=absent
