---
- hosts:  all
  become: true
  tasks:

  - name: Update apt-cache
    apt: 
      force_apt_get: yes
      update_cache:  yes

  - name: Upgrade apt
    apt: 
      force_apt_get: yes
      upgrade:       dist
