---
- hosts: grafana 
  become: true
  tasks:
    - name: Check/Install prerequisites
      apt: 
        name: apt-transport-https 
        state: present
        update_cache: yes

    - name: Check/Install prerequisites, software-properties-common
      apt: 
        name: software-properties-common 
        state: present

    - name: Check/Install prerequisites, wget
      apt: 
        name: wget 
        state: present
        update_cache: yes

    - name: add grafana gpg key
      shell: wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
        warn=false
        
    - name: add grafana stable repo 
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        filename: grafana

    - name: Update apt cache 
      apt: update_cache=yes

    - name: Install grafana
      apt: 
        name: grafana
        state: present
        update_cache: yes

    - name: Enable/Start grafana service
      service:
        name: grafana-server
        enabled: yes
        state: started

# https://grafana.com/docs/grafana/latest/installation/debian/

# https://grafana.com/grafana/download
# sudo apt-get install -y adduser libfontconfig1
# wget https://dl.grafana.com/oss/release/grafana_7.1.5_amd64.deb
# sudo dpkg -i grafana_7.1.5_amd64.deb
