---
- hosts: nginx
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: true
    - name: start nginx
      service:
          name: nginx
          state: started
    - name: copy the nginx config file and restart nginx
      copy:
        src: ./files/config/static_site.cfg
        dest: /etc/nginx/sites-available/static_site.cfg
    - name: create symlink
      file:
        src: /etc/nginx/sites-available/static_site.cfg
        dest: /etc/nginx/sites-enabled/default
        state: link
    - name: copy the content of the web site
      copy:
        src: ./files/config/static-site/
        dest: /home/foo/static-site
    - name: restart nginx
      service:
        name: nginx
        state: restarted
        
# https://code-maven.com/install-and-configure-nginx-using-ansible
