---
- hosts: nginx
  become: true
  tasks:
    - name: stop nginx
      service:
        name: nginx
        state: stopped
    - name: ensure nginx is not installed
      apt: name=nginx state=absent
